#!/usr/bin/env bash
# conjur-tf.sh — orchestrator for the Conjur Cloud Terraform workflow
#
# Usage:
#   ./scripts/conjur-tf.sh build-provider  # compile local provider fork
#   ./scripts/conjur-tf.sh plan            # terraform plan
#   ./scripts/conjur-tf.sh create          # terraform apply
#   ./scripts/conjur-tf.sh destroy         # terraform destroy
#   ./scripts/conjur-tf.sh output          # terraform output -json
#
# Prerequisites:
#   - common.env sourced (or exported) before running, OR present at repo root
#   - `conjur login` completed before plan / create / destroy
#   - Go installed (for build-provider)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TF_DIR="${ROOT_DIR}/terraform"
BUILD_DIR="${ROOT_DIR}/.build"
COMMON_ENV="${ROOT_DIR}/common.env"
DEV_RC="${ROOT_DIR}/.terraform-dev.rc"

# ── Load common.env ───────────────────────────────────────────────────────────

[[ -f "${COMMON_ENV}" ]] || {
  echo "ERROR: ${COMMON_ENV} not found."
  echo "       Copy common.env.example to common.env and fill in CONJUR_TENANT."
  exit 1
}
# shellcheck disable=SC1090
source "${COMMON_ENV}"

: "${CONJUR_TENANT:?CONJUR_TENANT must be set in common.env}"
: "${CONJUR_PROVIDER_SRC_DIR:?CONJUR_PROVIDER_SRC_DIR must be set in common.env (path to terraform-provider-conjur fork)}"

PROVIDER_BINARY="${BUILD_DIR}/terraform-provider-conjur"

# ── Helpers ───────────────────────────────────────────────────────────────────

require_conjur_login() {
  echo "==> Checking Conjur CLI session..."
  if ! conjur whoami >/dev/null 2>&1; then
    echo "ERROR: Conjur CLI is not authenticated."
    echo "       Run 'conjur login' and retry."
    exit 1
  fi
  echo "    Session active."
}

require_provider_binary() {
  [[ -f "${PROVIDER_BINARY}" ]] || {
    echo "ERROR: Provider binary not found at ${PROVIDER_BINARY}"
    echo "       Run: ./scripts/conjur-tf.sh build-provider"
    exit 1
  }
}

write_dev_rc() {
  cat > "${DEV_RC}" <<EOF
# Auto-generated by scripts/conjur-tf.sh — do not edit by hand.
provider_installation {
  dev_overrides {
    "cyberark/conjur" = "${BUILD_DIR}"
  }
  direct {}
}
EOF
}

run_terraform() {
  local subcmd="$1"; shift

  write_dev_rc
  export TF_CLI_CONFIG_FILE="${DEV_RC}"

  cd "${TF_DIR}"
  terraform "${subcmd}" "$@"
}

# ── Commands ──────────────────────────────────────────────────────────────────

cmd_build_provider() {
  [[ -d "${CONJUR_PROVIDER_SRC_DIR}" ]] || {
    echo "ERROR: CONJUR_PROVIDER_SRC_DIR (${CONJUR_PROVIDER_SRC_DIR}) does not exist."
    exit 1
  }

  if ! command -v go >/dev/null 2>&1; then
    echo "ERROR: 'go' not found in PATH. Install Go and retry."
    exit 1
  fi

  echo "==> Building terraform-provider-conjur..."
  echo "    Source: ${CONJUR_PROVIDER_SRC_DIR}"
  echo "    Output: ${PROVIDER_BINARY}"

  mkdir -p "${BUILD_DIR}"
  (cd "${CONJUR_PROVIDER_SRC_DIR}" && go build -o "${PROVIDER_BINARY}" .)

  echo "    Build complete."
  "${PROVIDER_BINARY}" --version 2>/dev/null || true
}

cmd_plan() {
  require_conjur_login
  require_provider_binary
  echo "==> Running terraform plan..."
  run_terraform plan
}

cmd_create() {
  require_conjur_login
  require_provider_binary
  echo "==> Running terraform apply..."
  run_terraform apply -auto-approve
}

cmd_destroy() {
  require_conjur_login
  require_provider_binary
  echo "==> Running terraform destroy..."
  run_terraform destroy -auto-approve
}

cmd_output() {
  require_provider_binary
  run_terraform output -json
}

usage() {
  cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  build-provider   Compile the local terraform-provider-conjur fork to .build/
  plan             Run terraform plan (requires conjur login)
  create           Run terraform apply  (requires conjur login)
  destroy          Run terraform destroy (requires conjur login)
  output           Show terraform output as JSON

Environment (via common.env):
  CONJUR_TENANT              Conjur Cloud tenant name
  CONJUR_PROVIDER_SRC_DIR   Path to local terraform-provider-conjur fork
  TF_VAR_*                   Passed automatically to terraform
EOF
  exit 1
}

# ── Dispatch ──────────────────────────────────────────────────────────────────

ACTION="${1:-}"
case "${ACTION}" in
  build-provider) cmd_build_provider ;;
  plan)           cmd_plan           ;;
  create)         cmd_create         ;;
  destroy)        cmd_destroy        ;;
  output)         cmd_output         ;;
  *)              usage              ;;
esac
