#!/usr/bin/env bash
# conjur-tf.sh — orchestrator for the Conjur Cloud Terraform workflow
#
# Usage:
#   ./scripts/conjur-tf.sh build-provider  # compile local provider fork (needed for fixes not yet published)
#   ./scripts/conjur-tf.sh init            # terraform init (published provider only; skip when using local build)
#   ./scripts/conjur-tf.sh plan            # terraform plan
#   ./scripts/conjur-tf.sh create          # terraform apply
#   ./scripts/conjur-tf.sh destroy         # terraform destroy
#   ./scripts/conjur-tf.sh output          # terraform output -json
#
# Provider selection (automatic):
#   If .build/terraform-provider-conjur exists, it is used via dev_overrides.
#   Otherwise the published cyberark/conjur provider is used (requires `init` first).
#
# Prerequisites:
#   - common.env present at repo root (copy from common.env.example)
#   - `conjur login` completed before plan / create / destroy
#   - Go installed (for build-provider)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TF_DIR="${ROOT_DIR}/terraform"
BUILD_DIR="${ROOT_DIR}/.build"
PROVIDER_BINARY="${BUILD_DIR}/terraform-provider-conjur"
DEV_RC="${ROOT_DIR}/.terraform-dev.rc"
COMMON_ENV="${ROOT_DIR}/common.env"

# ── Load common.env ───────────────────────────────────────────────────────────

[[ -f "${COMMON_ENV}" ]] || {
  echo "ERROR: ${COMMON_ENV} not found."
  echo "       Copy common.env.example to common.env and fill in CONJUR_TENANT."
  exit 1
}
# shellcheck disable=SC1090
source "${COMMON_ENV}"

: "${CONJUR_TENANT:?CONJUR_TENANT must be set in common.env}"

# ── Helpers ───────────────────────────────────────────────────────────────────

require_conjur_login() {
  echo "==> Checking Conjur CLI session..."
  if ! conjur whoami >/dev/null 2>&1; then
    echo "ERROR: Conjur CLI is not authenticated."
    echo "       Run 'conjur login' and retry."
    exit 1
  fi
  echo "    Session active."
}

# Write a .terraformrc that points dev_overrides at the local binary directory.
write_dev_rc() {
  cat > "${DEV_RC}" <<EOF
# Auto-generated by scripts/conjur-tf.sh — do not edit by hand.
provider_installation {
  dev_overrides {
    "cyberark/conjur" = "${BUILD_DIR}"
  }
  direct {}
}
EOF
}

# Run terraform with the appropriate config: dev_overrides if a local binary
# exists, plain published provider otherwise.
run_terraform() {
  local subcmd="$1"; shift

  if [[ -f "${PROVIDER_BINARY}" ]]; then
    write_dev_rc
    TF_CLI_CONFIG_FILE="${DEV_RC}" terraform -chdir="${TF_DIR}" "${subcmd}" "$@"
  else
    terraform -chdir="${TF_DIR}" "${subcmd}" "$@"
  fi
}

# ── Commands ──────────────────────────────────────────────────────────────────

cmd_build_provider() {
  : "${CONJUR_PROVIDER_SRC_DIR:?CONJUR_PROVIDER_SRC_DIR must be set in common.env (path to terraform-provider-conjur fork)}"
  [[ -d "${CONJUR_PROVIDER_SRC_DIR}" ]] || {
    echo "ERROR: CONJUR_PROVIDER_SRC_DIR (${CONJUR_PROVIDER_SRC_DIR}) does not exist."
    exit 1
  }
  if ! command -v go >/dev/null 2>&1; then
    echo "ERROR: 'go' not found in PATH. Install Go and retry."
    exit 1
  fi

  echo "==> Building terraform-provider-conjur..."
  echo "    Source: ${CONJUR_PROVIDER_SRC_DIR}"
  echo "    Output: ${PROVIDER_BINARY}"
  mkdir -p "${BUILD_DIR}"
  (cd "${CONJUR_PROVIDER_SRC_DIR}" && go build -o "${PROVIDER_BINARY}" .)
  echo "    Build complete. All subsequent runs will use this local binary."
  echo "    Delete .build/ to revert to the published provider."
}

cmd_init() {
  if [[ -f "${PROVIDER_BINARY}" ]]; then
    echo "NOTE: Local provider binary detected — 'init' is not needed for dev_overrides."
    echo "      Run 'plan' directly. Delete .build/ if you want to use the published provider."
    exit 0
  fi
  echo "==> Running terraform init..."
  run_terraform init -upgrade
}

cmd_plan() {
  require_conjur_login
  if [[ -f "${PROVIDER_BINARY}" ]]; then
    echo "==> Running terraform plan (local provider build)..."
  else
    echo "==> Running terraform plan (published provider)..."
  fi
  run_terraform plan
}

cmd_create() {
  require_conjur_login
  echo "==> Running terraform apply..."
  run_terraform apply -auto-approve
}

cmd_destroy() {
  require_conjur_login
  echo "==> Running terraform destroy..."
  run_terraform destroy -auto-approve
}

cmd_output() {
  run_terraform output -json
}

usage() {
  cat <<EOF
Usage: $(basename "$0") <command>

Commands:
  build-provider   Compile the local provider fork to .build/ (use when a fix
                   is needed that has not yet been published to the registry)
  init             Download the published provider (skip when using local build)
  plan             Run terraform plan  (requires conjur login)
  create           Run terraform apply (requires conjur login)
  destroy          Run terraform destroy (requires conjur login)
  output           Show terraform output as JSON

Provider selection:
  If .build/terraform-provider-conjur exists it is used automatically via
  dev_overrides. Delete .build/ to revert to the published provider.

Environment (set in common.env):
  CONJUR_TENANT              Conjur Cloud tenant name
  CONJUR_APPLIANCE_URL       Derived from CONJUR_TENANT
  CONJUR_ACCOUNT             Typically "conjur"
  CONJUR_PROVIDER_SRC_DIR    Path to local provider fork (build-provider only)
  TF_VAR_*                   Passed automatically to Terraform
EOF
  exit 1
}

# ── Dispatch ──────────────────────────────────────────────────────────────────

ACTION="${1:-}"
case "${ACTION}" in
  build-provider) cmd_build_provider ;;
  init)           cmd_init           ;;
  plan)           cmd_plan           ;;
  create)         cmd_create         ;;
  destroy)        cmd_destroy        ;;
  output)         cmd_output         ;;
  *)              usage              ;;
esac
